version: '3.8'

services:
  backend:
    image: eelarve-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - eelarve-network

networks:
  eelarve-network:
    driver: bridge